default:
  image: python:3.8.5-slim-buster
  before_script:
    - apt-get update
    - apt-get install -y libpq-dev gcc gnupg git
    - pip install poetry
    - poetry install

test-dev:
  script:
    - poetry run pytest -vv -s --log-cli-level DEBUG --log-level DEBUG --cov=cic_types --cov-fail-under=90 tests